# Generated by Django 3.0.8 on 2022-11-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='levels',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(default='General', max_length=30),
        ),
        migrations.CreateModel(
            name='NewsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('description', models.TextField(default='Hi')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.News')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
    ]
