# Generated by Django 3.0.8 on 2023-03-06 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=400)),
                ('code', models.CharField(default='', max_length=400)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Hi', max_length=100)),
                ('levels', models.IntegerField(default=170)),
                ('category', models.CharField(default='Java', max_length=30)),
                ('contentType', models.CharField(default='Tech', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(default='General', max_length=30)),
                ('contentType', models.CharField(default='WORLD NEWS', max_length=30)),
                ('imageLink', models.CharField(default='Hi', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEntertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(default='General', max_length=30)),
                ('contentType', models.CharField(default='CELEBRITY', max_length=30)),
                ('imageLink', models.CharField(default='Hi', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(default='General', max_length=30)),
                ('contentType', models.CharField(default='TECHNOLOGY NEWS', max_length=30)),
                ('imageLink', models.CharField(default='Hi', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('time_zn', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=8)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('time_zn', models.CharField(max_length=30)),
                ('meetingLink', models.URLField(max_length=400)),
                ('is_teklrn_authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(through='webapp.TeacherCourse', to='webapp.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentCourseVideoBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=170)),
                ('videoPresent', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=170)),
                ('date_joined', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='webapp.StudentCourse', to='webapp.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NewsTechnologyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('description', models.TextField(default='Hi')),
                ('imageLink', models.CharField(default='', max_length=400)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.NewsTechnology')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='NewsLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Language')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('description', models.TextField(default='Hi')),
                ('imageLink', models.CharField(default='', max_length=400)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.News')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='NewsEntertainmentLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('description', models.TextField(default='Hi')),
                ('imageLink', models.CharField(default='', max_length=400)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.NewsEntertainment')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=4)),
                ('reviewCount', models.IntegerField(default=46739)),
                ('videoPresent', models.BooleanField(default=False)),
                ('videoFree', models.BooleanField(default=0)),
                ('videoLink', models.CharField(default='Hi', max_length=400)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='webapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='webapp.Course')),
            ],
        ),
    ]
