# Generated by Django 3.0.8 on 2020-08-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_teklrn_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
