# Generated by Django 2.2.3 on 2019-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='meetingLink',
            field=models.URLField(default='https://hbc.zoom.us/j/627443986', max_length=400),
            preserve_default=False,
        ),
    ]
