# Generated by Django 3.0.8 on 2020-09-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_teacher_is_teklrn_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Java', max_length=30),
        ),
    ]
