# Generated by Django 3.0.8 on 2020-11-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_courselevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='rating',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='reviewCount',
            field=models.IntegerField(default=46739),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='videoPresent',
            field=models.BooleanField(default=False),
        ),
    ]
