# Generated by Django 3.0.8 on 2023-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_personvideolinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='personvideolinks',
            name='imgLink',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='personvideolinks',
            name='txt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
