# Generated by Django 3.0.8 on 2020-11-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_studentcoursevideobookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='videoFree',
            field=models.BooleanField(default=0),
        ),
    ]
