# Generated by Django 3.0.8 on 2023-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20230410_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSearchUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
