# Generated by Django 3.0.8 on 2023-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_newssearchurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssearchurls',
            name='rule',
            field=models.CharField(default='', max_length=5),
        ),
    ]
