# Generated by Django 3.0.8 on 2020-11-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_courselevel_videofree'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='videoLink',
            field=models.CharField(default='Hi', max_length=400),
        ),
    ]
