# Generated by Django 3.0.8 on 2021-02-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_courselevel_videolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
