# Generated by Django 3.0.8 on 2023-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_newssearchurls_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(default='General', max_length=30)),
                ('contentType', models.CharField(default='FINANCIAL', max_length=30)),
                ('imageLink', models.CharField(default='Hi', max_length=400)),
            ],
        ),
    ]
