# Generated by Django 3.0.8 on 2023-05-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_newsfinancial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFinancialLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1)),
                ('description', models.TextField(default='Hi')),
                ('imageLink', models.CharField(default='', max_length=400)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.NewsFinancial')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
    ]
