# Generated by Django 3.0.8 on 2021-02-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_careerroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerroles',
            name='courses',
            field=models.ManyToManyField(to='webapp.Course'),
        ),
    ]
