# Generated by Django 3.0.8 on 2023-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_newsfinanciallevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslinks',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
