# Generated by Django 3.0.8 on 2023-05-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20230509_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslinks',
            name='category',
        ),
    ]
