# Generated by Django 3.0.8 on 2023-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_newslinks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslinks',
            name='category',
            field=models.CharField(default='NEWS', max_length=20),
        ),
    ]
