# Generated by Django 3.0.8 on 2022-11-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210902_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Hi', max_length=100)),
                ('levels', models.IntegerField(default=170)),
                ('category', models.CharField(default='Java', max_length=30)),
                ('contentType', models.CharField(default='Tech', max_length=30)),
            ],
        ),
    ]
