# Generated by Django 3.0.8 on 2023-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_newsfinancial_contenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNewsVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=1000)),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
