# Generated by Django 3.0.8 on 2023-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_dailynewsvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynewsvideos',
            name='imgurl',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
