# Generated by Django 3.0.8 on 2023-05-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_dailynewsvideos_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailynewsvideos',
            old_name='imgurl',
            new_name='imgLink',
        ),
        migrations.RenameField(
            model_name='dailynewsvideos',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='dailynewsvideos',
            old_name='title',
            new_name='person',
        ),
        migrations.AddField(
            model_name='dailynewsvideos',
            name='txt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
