# Generated by Django 3.0.8 on 2023-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20230529_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advertisement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='business_name',
            field=models.CharField(default='Default', max_length=60),
        ),
    ]
