# Generated by Django 3.0.8 on 2023-09-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20230926_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerroles',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='Java', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='contentType',
            field=models.CharField(default='Tech', max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='contentType',
            field=models.CharField(default='WORLD NEWS', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsentertainment',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsentertainment',
            name='contentType',
            field=models.CharField(default='CELEBRITY', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsentertainment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsfinancial',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsfinancial',
            name='contentType',
            field=models.CharField(default='FINANCIAL [en]', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsfinancial',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newstechnology',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='newstechnology',
            name='contentType',
            field=models.CharField(default='TECHNOLOGY NEWS', max_length=100),
        ),
        migrations.AlterField(
            model_name='newstechnology',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
