# Generated by Django 3.0.8 on 2023-09-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20230929_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
