# Generated by Django 3.0.8 on 2023-09-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20230929_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslevel',
            name='imageLink',
            field=models.CharField(default='', max_length=500),
        ),
    ]
