# Generated by Django 3.0.8 on 2023-09-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20230929_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslevel',
            name='imageLink',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
