# Generated by Django 3.0.8 on 2023-09-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20230929_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
