# Generated by Django 3.0.8 on 2023-09-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20230929_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsentertainment',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
