# Generated by Django 3.0.8 on 2023-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20230929_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfinancial',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
