# Generated by Django 3.0.8 on 2023-09-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20230929_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnewslinks',
            name='link',
            field=models.CharField(max_length=2000),
        ),
    ]
