# Generated by Django 3.0.8 on 2023-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20230930_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvideolinks',
            name='imgLink',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='personvideolinks',
            name='link',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='personvideolinks',
            name='txt',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
