# Generated by Django 3.0.8 on 2023-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20230930_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstechnology',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
