# Generated by Django 3.0.8 on 2023-10-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_auto_20231001_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=1000)),
                ('payed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
    ]
