# Generated by Django 3.0.8 on 2023-10-08 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_studentads'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentads',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 10, 17, 14, 704983)),
        ),
    ]
