# Generated by Django 3.0.8 on 2023-10-16 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_studentads_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cust_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='one_click',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentads',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 13, 4, 54, 698791)),
        ),
    ]
